language: node_js
node_js:
  - 5.1
services:
  - postgresql
before_script:
  - psql -c 'create database ngis_test;' -U postgres
  - cp db/config.example.js db/config.js
  - cp src/shared/config.example.js src/shared/config.js
